### ISSUE TITLE
Doesn't Support Commonjs

### ISSUE THREAD

**Issue by KingMaxine** [scttcper/qbittorrent#102]
I was using another qBittorent package for my app that supports Commonjs. But this package doesn't support Commonjs and my typescript code is compiling to Commonjs and I can't change the typescript code to emit esm module JavaScript because the codebase is extremely large and I don't want to break other things.

Any walk around?

**Comment by scttcper** [comment]
You could probably fork and package it how you want, you can also install this package directly from github with npm once forking. Not going to support commonjs anymore.

**Comment by sachaw** [comment]
@KingMaxine typescript can ingest ESM and transpile to CJS, so there shouldn't be an issue using this package.

**Comment by KingMaxine** [comment]
@sachaw apparent there is, the package doesn't support anything Commonjs but I know what I can do now
I think I will fork it
