### ISSUE TITLE
Make _normalizeTorrentData public or include raw torrent data in normalized object

### ISSUE THREAD

**Issue by Pajn** [scttcper/qbittorrent#111]
I'd like to primarily work with the normalized data but need some client-specific fields as well, one example is `tags`.
With current design I'd have to fetch the same data twice which seem unneccecary.

It would be nice if either  `_normalizeTorrentData` was public so that I could use it myself after fetching with `listTorrents` or that `NormalizedTorrent` included a `raw: Record<string, any>` property (or similar)

**Comment by scttcper** [comment]
closed in #113
