### ISSUE TITLE
`listTorrents` doesn't respect empty strings as valid inputs for `category` and `tag`

### ISSUE THREAD

**Issue by fr3fou** [scttcper/qbittorrent#114]
https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-4.1)#get-torrent-list

![image](https://user-images.githubusercontent.com/1344906/206881657-85078fd1-3892-44cb-9594-725b77a26a6c.png)

Both the `tag` and `category` fields can accept an empty string, which the current implementation completely ignores:

https://github.com/scttcper/qbittorrent/blob/593035a94b470a1e01cb4eab3c6850ec841613a5/src/qbittorrent.ts#L172-L178

**Comment by scttcper** [comment]
Thanks for reporting, just as a heads up, this client does not seem to work well with the recently released version of qbittorrent 4.5
