### ISSUE TITLE
HTTPError: Response code 405 (Method Not Allowed)

### ISSUE THREAD

**Issue by FibonacciFox** [scttcper/qbittorrent#115]
All API methods only allows GET or POST methods. Use POST when you are mutating some state (or when your request is too big to fit into GET) and use GET otherwise. Starting with qBittorrent v4.4.4, server will return 405 Method Not Allowed when you used the wrong request method.

removeTorrent, pauseTorrent, resumeTorrent.....

**Comment by scttcper** [comment]
fixed in https://github.com/scttcper/qbittorrent/pull/116
