### ISSUE TITLE
Long-lived clients do not handle session cookie expiration

### ISSUE THREAD

**Issue by JoshGlazebrook** [scttcper/qbittorrent#86]
QBittorrent seems to have a default timeout of 3600 seconds (1 hour) for sessions when logging into the webui. 

Based on the code, it does an initial login and for each request done with the same client instance, if there is a cookie set locally `this._sid` it sets it as the Cookie header. However after the cookie expires, it doesn't re-login, it just keeps using the same expired cookie.

Potential solution for this is to make note of the expiration of the cookie itself and re-login when needed?

**Comment by Schaka** [comment]
Just wanted to say thanks for this issue as I couldn't find session expiry time in the docs and had a similar issue with the using the API directly
