### ISSUE TITLE
Problem importing from `types`

### ISSUE THREAD

**Issue by sachaw** [scttcper/qbittorrent#92]
My app's throwing a not found error in development with the following statement (but build succeeds)
```ts
import { TorrentState } from "@ctrl/qbittorrent/dist/types";
``` 
May I suggest using the exports tag of `package.json` in favor of the obsolete `main` tag which should fix this.
Some reading:
https://dev.to/binjospookie/exports-in-package-json-1fl2
https://nodejs.org/api/packages.html
https://medium.com/swlh/npm-new-package-json-exports-field-1a7d1f489ccf

Whilst we're at it, why not switch the package to an ESModule? do you have any need to use commonjs, if not I'd be happy to commit the required changes.

Regards.

**Comment by scttcper** [comment]
Those Enums should be exported from `import { TorrentState } from "@ctrl/qbittorrent` 
The only problem I see is I have a `import { TorrentState } from '@ctrl/shared-torrent';` that is the normalized state enum. You really shouldn't need to import deep from the dist folder like that, let me know of anything you need exported at the top level.

The module will be made into an esmodule when got 12 comes out of beta. Got 12 will also be ESM only.

**Comment by sachaw** [comment]
Thanks for that, when you do make the switch to ESM, might I suggest `form-data-encoder` and
`formdata-node` as a modern replacement for `formdata`.

Further info: https://github.com/sindresorhus/got/discussions/1877
