### ISSUE TITLE
Add tag optional parameter to /torrents/info

### ISSUE THREAD

**Issue by shanke0303** [scttcper/qbittorrent#96]
Hi, I found that the 'tag' parameter of listTorrents function is missing.
See qBittorrent API documentation:[https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-4.1)#api-v283](https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-4.1)#api-v283)

**Comment by scttcper** [comment]
need to refactor that function in the next version, but i've slapped it on there
